#! /usr/bin/env python3
import sys, os
sys.path.append("./lib")

from autokey.qt5app import Application
HOME_DIR = os.path.expanduser("~")
target_dir = os.path.expanduser("~/.local/share/autokey")

a = Application()
a.main()

sys.exit(0)
